### ISSUE TITLE
is this working right now ?

### ISSUE THREAD

**Issue by ivanzamoraarias** [owenniblock/sonic-pi-js#1]
Just asking , wanna play with it , more fun using JS 👍

**Comment by owenniblock** [comment]
Sorry I missed this question - I gave up on this because I decided the limitations were too large. It's fun to mess around with but to do anything more complex I found I was having to hack more and more.

I think the real way to approach this would be to use the sonic-pi engine and write a wrapper on top that does the same as the Ruby engine but in a JS kinda way.

So in conclusion:
It kinda works.
It has limitations (like properly accessing the loops and stuff)
It's clunky and not the right approach.
It was fun to mess around with for a few days 🙂
